minio:
  image: minio/minio
  volumes:
    - $PWD/export:/export
    - $PWD/minioconf:/.minio


backupdb:
  environment:
    CRON_TIME: 0 0 * * *
    #INIT_BACKUP: 'true'
    INIT_RESTORE_LATEST: 'true'
    #INIT_RESTORE_URL: 'myminio/databases/imimat.sql'
    MINIO_HOST: myminio
    MINIO_HOST_URL: 'http://minio:9000'
    MINIO_ACCESS_KEY: 'PQ5J0TF5STG1Z6R6UZ87'
    MINIO_SECRET_KEY: 'R2pKxxoVv3APryH+4BaKrcXuF615VqS/5d5+sB/i'
    MINIO_BUCKET: 'resticb11'
    BACKUP_DIRS: '/app'
    USE_RESTIC: 'true'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: fimim.os=ubuntu
  links:
    - minio:minio
  tty: true
  build: .
  command: /run.sh
  #image: jmcarbo/docker-volume-backup
  volumes_from:
    - test

test:
  volumes:
    - app:/app
  image: ubuntu
  command: /bin/bash
  tty: true
  stdin_open: true 
